services:
  db:
    image: 'postgres'
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./payload-cms/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  payload-cms:
    image: hasithd/hasith-portfolio:payload-cms
    ports:
      - 3000:3000
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PAYLOAD_SECRET=${PAYLOAD_SECRET}
      - DATABASE_URI=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}      
      - PAYLOAD_PUBLIC_EXTERNAL_SERVER_URL=${PAYLOAD_PUBLIC_EXTERNAL_SERVER_URL}
    command: /bin/sh -c "pnpm migrate && pnpm serve"
  website:
    image: hasithd/hasith-portfolio:website
    ports:
      - 4321:80