services:
  web:
    platform: linux/amd64
    image: 'portfolio/website'
    build:
      context: ./ 
      dockerfile: ./apps/website/dockerfile.prod
    ports:
      - 4321:80
    environment:
      - ENV=production
    command: ["nginx", "-g", "daemon off;"]  
    restart: always 
    depends_on:
          - db