FROM node:lts AS base
WORKDIR /app

COPY package.json ./
COPY pnpm-lock.yaml ./

#install the dependencies 
FROM base AS prod-deps
RUN npm install -g pnpm
RUN pnpm install --frozen-lockfile --prod

#Build with the depth
FROM base AS build-deps
RUN npm install -g pnpm
RUN pnpm install --frozen-lockfile

FROM build-deps AS build
COPY . .
RUN pnpm run build

# Stage 3: Serve the static site with nginx
FROM nginx:alpine AS production

COPY --from=build /app/dist /usr/share/nginx/html

# Expose port 4321 for HTTP traffic
EXPOSE 4321

# Start nginx
CMD ["nginx", "-g", "daemon off;"]

