/** @type {import('tailwindcss').Config} */
const config = {
  darkMode: ['class'],
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}', './src/stories/**/*.{js,ts,svelte}'],
  safelist: ['dark'],
  theme: {
    screens: {
      'sm': '640px',
      'md': '768px',
      'lg': '1024px',
      'xl': '1280px',
      '2xl': '1400px',
    },
    container: {
      center: true,
      padding: '2rem',
    },
    extend: {
      fontFamily: {
        body: ['poppins', 'sans-serif'],
        display: ['montserrat alternates', 'sans-serif'],
      },
      fontWeight: {
        light: '300',
        normal: '400',
        medium: '500',
        semibold: '600',
        bold: '700',
        extrabold: '800',
        black: '900',
      },
      fontSize: {
        'display-1-mobile': '90px',
        'display-1-desktop': '150px',
        'display-2-mobile': '75px',
        'display-2-desktop': '125px',
        'display-3-mobile': '60px',
        'display-3-desktop': '100px',
        'large-1-mobile': '48px',
        'large-1-desktop': '55px',
        'large-2-mobile': '40px',
        'large-2-desktop': '50px',
        'large-3-mobile': '35px',
        'large-3-desktop': '45px',
        'h1-mobile': '35px',
        'h1-desktop': '40px',
        'h2-mobile': '31px',
        'h2-desktop': '34px',
        'h3-mobile': '28px',
        'h3-desktop': '32px',
        'h4-mobile': '25px',
        'h4-desktop': '30px',
        'h5-mobile': '22px',
        'h5-desktop': '28px',
        'subeheading-1-mobile': '19px',
        'subeheading-1-desktop': '22px',
        'suheading-2-mobile': '16px',
        'suheading-2-desktop': '20px',
        'suheading-3-mobile': '14px',
        'suheading-3-desktop': '18px',
        'suheading-4-mobile': '12px',
        'suheading-4-desktop': '16px',
        'suheading-5-mobile': '10px',
        'suheading-5-desktop': '14px',
        'p1-mobile': '14px',
        'p1-desktop': '18px',
        'p2-mobile': '12px',
        'p2-desktop': '16px',
        'p3-mobile': '10px',
        'p3-desktop': '14px',
        'p4-mobile': '8px',
        'p4-desktop': '12px',
        'p5-mobile': '7px',
        'p5-desktop': '10px',
      },
      colors: {
        'primary-100': '#AAEEFA',
        'primary-200': '#61D1E5',
        'primary-400': '#57BBCD',
        'primary-600': '#368593',
        'primary-800': '#16353B',
        'secondary-100': '#EEEEDA',
        'secondary-200': '#D7D4B5',
        'secondary-400': '#AEAA81',
        'secondary-600': '#8C864B',
        'secondary-800': '#595530',
        'neutral-50': '#FAFAFA',
        'neutral-100': '#F5F5F5',
        'neutral-200': '#E5E5E5',
        'neutral-300': '#D4D4D4',
        'neutral-400': '#A3A3A3',
        'neutral-500': '#737373',
        'neutral-600': '#525252',
        'neutral-700': '#404040',
        'neutral-800': '#262626',
        'neutral-900': '#171717',
        'border': 'hsl(var(--border) / <alpha-value>)',
        'input': 'hsl(var(--input) / <alpha-value>)',
        'ring': 'hsl(var(--ring) / <alpha-value>)',
        'background': 'hsl(var(--background) / <alpha-value>)',
        'foreground': 'hsl(var(--foreground) / <alpha-value>)',
        'primary': {
          DEFAULT: 'hsl(var(--primary) / <alpha-value>)',
          foreground: 'hsl(var(--primary-foreground) / <alpha-value>)',
        },
        'secondary': {
          DEFAULT: 'hsl(var(--secondary) / <alpha-value>)',
          foreground: 'hsl(var(--secondary-foreground) / <alpha-value>)',
        },
        'destructive': {
          DEFAULT: 'hsl(var(--destructive) / <alpha-value>)',
          foreground: 'hsl(var(--destructive-foreground) / <alpha-value>)',
        },
        'muted': {
          DEFAULT: 'hsl(var(--muted) / <alpha-value>)',
          foreground: 'hsl(var(--muted-foreground) / <alpha-value>)',
        },
        'accent': {
          DEFAULT: 'hsl(var(--accent) / <alpha-value>)',
          foreground: 'hsl(var(--accent-foreground) / <alpha-value>)',
        },
        'popover': {
          DEFAULT: 'hsl(var(--popover) / <alpha-value>)',
          foreground: 'hsl(var(--popover-foreground) / <alpha-value>)',
        },
        'card': {
          DEFAULT: 'hsl(var(--card) / <alpha-value>)',
          foreground: 'hsl(var(--card-foreground) / <alpha-value>)',
        },
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      lineHeight: {
        heading: '1.2',
        subheading: '1.4',
        p: '1.6',
      },
    },
    variants: {
      extend: {
        fontSize: ['responsive'],
      },
    },
  },
}

export default config
